version: "3.3"
services:
  db-microservices:
    image: mysql:8.0.29
    restart: always
    environment:
      MYSQL_USER: "mysql"
      MYSQL_PASSWORD: "mysql"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - vol-db-microservices:/var/lib/mysql
# Volumes
volumes:
  vol-db-microservices:
